### ISSUE TITLE
number of fake players are not shown in 'Internet' browser

### ISSUE THREAD

**Issue by vanill4h** [yourmnbbn/smext-fakequeries#21]
Hi, as in the title, how i can fix that?

**Comment by yourmnbbn** [comment]
Hello, issue #4 is talking about the same thing, close this due to duplication. About the issue itself, currently there is no easy way to solve this, players count in the Internet tab works differently. If you're also a developer you can play around with [this repo](https://github.com/yourmnbbn/tiny-csgo-client) to manipulate the player count in the Internet browser.
